### ISSUE TITLE
Failed to import model. (Failed to load occt-import-js.)

### ISSUE THREAD

**Issue by vietvmo** [kovacsv/Online3DViewerExample#3]
hi @kovacsv
I have a 3D file in IGS and STP format but when I import it it gives an error, can I know why?

**Comment by vietvmo** [comment]
![image](https://github.com/kovacsv/Online3DViewerExamples/assets/107909942/391e4e11-dffd-4a0c-afd7-2537dd070d43)

**Comment by kovacsv** [comment]
Please check the external library handling part in the documentation:
https://kovacsv.github.io/Online3DViewer/Page_Usage.html
